### ISSUE TITLE
Debian install issue

### ISSUE THREAD

**Issue by fullmetalucard** [Alignak-monitoring-contrib/alignak-demo#26]
Hi there, I actually want to try alignak and installed it on a fresh new debian stretch, following your install tutorial.

Now several things after installation. Without doing anything (no configuration changes),  alignak service crashes directly. Taking a look at the alignak.ini file, i see that the path might be wrong :+1: 
```
_dist=/usr/local/
_dist_BIN=%(_dist)s/bin
_dist_ETC=%(_dist)s/etc/alignak
_dist_VAR=%(_dist)s/var/lib/alignak
_dist_RUN=%(_dist)s/var/run/alignak
_dist_LOG=%(_dist)s/var/log/alignak
```
Although part of alignak is installed in /usr/local/share/alignak.
So i replaced with matching places, bu now when i try to lauch alignak broker, here is what i see:

`Jan  7 10:18:07 alignak-test alignak-broker[28106]:   File "/usr/local/bin/alignak-broker", line 6, in <module>
Jan  7 10:18:07 alignak-test alignak-broker[28106]:     from pkg_resources import load_entry_point
Jan  7 10:18:07 alignak-test alignak-broker[28106]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
Jan  7 10:18:07 alignak-test alignak-receiver[28104]:     f(*args, **kwargs)
Jan  7 10:18:07 alignak-test alignak-receiver[28104]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
Jan  7 10:18:07 alignak-test alignak-receiver[28104]:     working_set = WorkingSet._build_master()
Jan  7 10:18:07 alignak-test alignak-receiver[28104]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
Jan  7 10:18:07 alignak-test alignak-receiver[28104]:     ws.require(__requires__)
Jan  7 10:18:07 alignak-test alignak-receiver[28104]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
Jan  7 10:18:07 alignak-test alignak-receiver[28104]:     needed = self.resolve(parse_requirements(requirements))
Jan  7 10:18:07 alignak-test alignak-receiver[28104]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
Jan  7 10:18:07 alignak-test alignak-receiver[28104]:     raise DistributionNotFound(req, requirers)
Jan  7 10:18:07 alignak-test systemd[1]: Failed to start Alignak reactionner master daemon instance.
Jan  7 10:18:07 alignak-test alignak-broker[28106]:     @_call_aside
Jan  7 10:18:07 alignak-test alignak-broker[28106]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
Jan  7 10:18:07 alignak-test alignak-broker[28106]:     f(*args, **kwargs)
Jan  7 10:18:07 alignak-test alignak-broker[28106]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
Jan  7 10:18:07 alignak-test alignak-broker[28106]:     working_set = WorkingSet._build_master()
Jan  7 10:18:07 alignak-test alignak-broker[28106]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
Jan  7 10:18:07 alignak-test alignak-broker[28106]:     ws.require(__requires__)
Jan  7 10:18:07 alignak-test alignak-broker[28106]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
Jan  7 10:18:07 alignak-test alignak-broker[28106]:     needed = self.resolve(parse_requirements(requirements))
Jan  7 10:18:07 alignak-test alignak-broker[28106]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
Jan  7 10:18:07 alignak-test alignak-broker[28106]:     raise DistributionNotFound(req, requirers)
Jan  7 10:18:07 alignak-test alignak-broker[28106]: pkg_resources.DistributionNotFound: The 'alignak==2.0.0' distribution was not found and is required by the application
Jan  7 10:18:07 alignak-test alignak-receiver[28104]: pkg_resources.DistributionNotFound: The 'alignak==2.0.0' distribution was not found and is required by the application
`

trying to etst configuration in CLI also ends with the same error:

`alignak-arbiter -V -e /usr/local/share/alignak/etc/alignak.ini
Traceback (most recent call last):
  File "/usr/local/bin/alignak-arbiter", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'alignak==2.0.0' distribution was not found and is required by the application
`

What's going wrong, might be a path problem ?

**Comment by fullmetalucard** [comment]
I must precise, I installed the packages with APT method, but alignak binary seems quite incomplete.
So I tried with "pip install alignak"
Now alignak works:
` alignak --help
alignak-environment command line interface::

    Usage:
        alignak [-h|--help]
`

Now arbiter fails on something I must find.

`alignak-arbiter -V -e /usr/local/share/alignak/etc/alignak.ini
Traceback (most recent call last):
  File "/usr/local/bin/alignak-arbiter", line 7, in <module>
    from alignak.bin.alignak_arbiter import main
  File "/usr/local/lib/python2.7/dist-packages/alignak/bin/alignak_arbiter.py", line 56, in <module>
    from alignak.daemons.arbiterdaemon import Arbiter
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 85, in <module>
    from alignak.daemon import Daemon
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 201, in <module>
    from alignak.http.daemon import HTTPDaemon, PortNotFree
  File "/usr/local/lib/python2.7/dist-packages/alignak/http/daemon.py", line 30, in <module>
    import cherrypy
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/__init__.py", line 73, in <module>
    from ._cptools import default_toolbox as tools, Tool
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cptools.py", line 33, in <module>
    from cherrypy.lib import auth_basic, auth_digest
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/auth_digest.py", line 26, in <module>
    from six.moves.urllib.parse import unquote_to_bytes
ImportError: cannot import name unquote_to_bytes
`

No instance is launched, nor none of the usual ports is listening.
I precise I'm very familiar with shinken, and just intend to test your fork.
For now I'm a bit lost :)
